### ISSUE TITLE
#2 Review - elección fuera de tiempo

### ISSUE THREAD

**Issue by Marcosreuquen** [JtoralesK/desafio-final-dwf-5#2]
Buenas tardes, Javi!!

Felicitaciones, ante todo, por llegar hasta este desafío! 
Hay dos cositas que estaría bueno que veas:
- Elección fuera de tiempo: 
> Cuando pasan los 3 segundos y no eligió su jugada, se muestra la elección previa y continúa el juego. Podrías agregarle una validación cuando se termina el tiempo que si no eligió, vuelva a las instrucciones.
- Mano elegida: 
> En el hover, las manos se rellenan (o se les va la transparencia), pero al darle click no se destacan de las demás. No es gran cosa, pero presta a confusión (como si no hubieras elegido).

Si podés chequealas y contestame el issue así lo veo de nuevo. 
Saludos!

**Comment by JtoralesK** [comment]
Buenos días, ahí trate de arreglarlo , lo que hice fue hacer un reset de
las jugadas para que si no se presiona nada pueda funcionar bien la función
que te elige jugadas random y no tome siempre la última jugada y , en el
caso de la elección de la jugada, lo que hice fue que al apretar la jugada
te la elija y elimine las otras, primero para que se note bien cuál
elegiste y no cree confusiones y por otra parte porque si dejaba las otras
se podría tocar varias jugadas que a la vez quedaron seleccionadas y
generaría más confusión. De esta forma creo pude solucionarlo..

**Comment by Marcosreuquen** [comment]
Buenas! Ahí volví a entrar y me tira este error:
![image](https://user-images.githubusercontent.com/75027556/139853590-e7dbc0fd-076c-4d49-974f-83a1e15e769e.png)
Creo que es porque se hace al comienzo de la partida y se carga el state como `null`
Fijate de ponerle algo como `const currentState = this.getState() || this.data;`
Cosa que si el usuario no tiene guardado nada en localStorage, tome algo como para inicializar.

**Comment by JtoralesK** [comment]
Si , ese error ya lo había resolvió creo , pasa que tuve unos problemas con
git y volví a otro tiempo , en el pasado , de mis comitt y perdí algunas
funciones jajaja , ahí lo volví a poner y funciona cuando empiezas de 0, o
al menos de forma local porque no lo pude probar desde la page de GitHub
porque ya tengo guardado datos, pero ya debería de estar
